name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java:
          - name: AdoptOpenJDK 8
            version: adopt@1.8
          - name: AdoptOpenJDK 11
            version: adopt@1.11
    name: With ${{ matrix.java.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java.version }}
      - uses: coursier/cache-action@v6
      - name: Lint
        run: sbt scalafmtCheckAll "rules2_12/scalafix --check"
      - name: Test
        run: sbt coverage tests/test coverageAggregate
      - uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
