name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v12
      - uses: coursier/cache-action@v6
      - name: Lint
        run: sbt scalafmtCheckAll "rules2_12/scalafix --check"
      - name: Test
        run: sbt coverage tests/test coverageAggregate
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
