name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Lint
        run: sbt scalafmtCheckAll "rules/scalafix --check"

      - name: Test
        run: sbt coverage tests/test coverageReport

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
