name: Release
on:
  push:
    branches: [master]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # Fetch all tags to help sbt-ci-release infer the snapshot version.
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v12
      - uses: coursier/cache-action@v6
      - name: Test
        run: sbt scalafmtCheck "rules/scalafix --check" +test
      - name: Publish ${{ github.ref }}
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: sbt ci-release
